spring.application.name=verify-service
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
server.servlet.context-path=/v1/verify
spring.datasource.url=jdbc:postgresql://localhost:5432/inji_verify?currentSchema=verify
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8081
spring.profiles.active=local

# The below configuration is set for VP request status long polling timeout set with env INJI_VP_REQUEST_LONG_POLLING_TIMEOUT, if not set the default value >
inji.vp-request.long-polling-timeout=${INJI_VP_REQUEST_LONG_POLLING_TIMEOUT:55000}
## Properties relayted to bank of brazil
govbr.bb.token.grant.type=client_credentials
govbr.bb.token.scope=webhook-mgi.requisicao
govbr.bb.token.auth=Basic ZXlKcFpDSTZJalJqWTJZME1XUXRPVEUxTmkwME1qRTBMU0lzSW1OdlpHbG5iMUIxWW14cFkyRmtiM0lpT2pBc0ltTnZaR2xuYjFOdlpuUjNZWEpsSWpveE5UTXhPVGNzSW5ObGNYVmxibU5wWVd4SmJuTjBZV3hoWTJGdklqb3hmUTpleUpwWkNJNkltWmxOV0kzWW1FdE9UWTROeTAwTldVNUxUa3pJaXdpWTI5a2FXZHZVSFZpYkdsallXUnZjaUk2TUN3aVkyOWthV2R2VTI5bWRIZGhjbVVpT2pFMU16RTVOeXdpYzJWeGRXVnVZMmxoYkVsdWMzUmhiR0ZqWVc4aU9qRXNJbk5sY1hWbGJtTnBZV3hEY21Wa1pXNWphV0ZzSWpveUxDSmhiV0pwWlc1MFpTSTZJbWh2Ylc5c2IyZGhZMkZ2SWl3aWFXRjBJam94TnpVNU9ESTJOalUzTVRFMmZR
govbr.bb.api.key=gw-dev-app-key
govbr.bb.client.cert-path=certs/client.crt
govbr.bb.client.key-path=certs/client.crt
govbr.bb.ca.cert-path=certs/ca.crt

mtls.client.keystore-path=C:\\Users\\NW165ZN\\Downloads\\Archive\\client-keystore.p12
mtls.client.keystore-password=changeit
mtls.client.truststore-path=C:\\Users\\NW165ZN\\Downloads\\Archive\\truststore.jks
mtls.client.truststore-password=changeit

# Audit properties
audit.enabled=${AUDIT_ENABLED:false}